// <auto-generated />
using System;
using AdvertisingService.DataAccess.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvertisingService.DataAccess.DAL.Migrations
{
    [DbContext(typeof(AdvertisementDbContext))]
    [Migration("20231016183707_MakeStreetNumberOptional")]
    partial class MakeStreetNumberOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("int")
                        .HasColumnName("advertisementId");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("district");

                    b.Property<short>("PostalCode")
                        .HasColumnType("smallint")
                        .HasColumnName("postalCode");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("region");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar")
                        .HasColumnName("streetName");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar")
                        .HasColumnName("streetNumber");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar")
                        .HasColumnName("unitNumber");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertisementId = 1,
                            City = "Budapest",
                            District = "XI.",
                            PostalCode = (short)1091,
                            Region = "Pest",
                            StreetName = "Király utca",
                            StreetNumber = "47.",
                            UnitNumber = "15."
                        },
                        new
                        {
                            Id = 2,
                            AdvertisementId = 2,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 3,
                            AdvertisementId = 3,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 4,
                            AdvertisementId = 4,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 5,
                            AdvertisementId = 5,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 6,
                            AdvertisementId = 6,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 7,
                            AdvertisementId = 7,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 8,
                            AdvertisementId = 8,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 9,
                            AdvertisementId = 9,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 10,
                            AdvertisementId = 10,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 11,
                            AdvertisementId = 11,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 12,
                            AdvertisementId = 12,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 13,
                            AdvertisementId = 13,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 14,
                            AdvertisementId = 14,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 15,
                            AdvertisementId = 15,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 16,
                            AdvertisementId = 16,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        },
                        new
                        {
                            Id = 17,
                            AdvertisementId = 17,
                            City = "Pécs",
                            PostalCode = (short)7600,
                            Region = "Baranya",
                            StreetName = "Kossuth utca",
                            StreetNumber = "12.",
                            UnitNumber = "10."
                        });
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertiserId")
                        .HasColumnType("int")
                        .HasColumnName("advertiserId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("description");

                    b.Property<bool>("Furnished")
                        .HasColumnType("bit")
                        .HasColumnName("furnished");

                    b.Property<int>("MonthlyPrice")
                        .HasColumnType("int")
                        .HasColumnName("monthlyPrice");

                    b.Property<double>("NumberOfRooms")
                        .HasColumnType("float")
                        .HasColumnName("numberOfRooms");

                    b.Property<bool>("Parking")
                        .HasColumnType("bit")
                        .HasColumnName("parking");

                    b.Property<double>("Size")
                        .HasColumnType("float")
                        .HasColumnName("size");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 16, 20, 37, 7, 430, DateTimeKind.Local).AddTicks(9942))
                        .HasColumnName("uploadDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertiserId = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = true,
                            MonthlyPrice = 250000,
                            NumberOfRooms = 3.0,
                            Parking = false,
                            Size = 70.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AdvertiserId = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu",
                            Furnished = false,
                            MonthlyPrice = 100000,
                            NumberOfRooms = 1.0,
                            Parking = true,
                            Size = 20.0,
                            UploadDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "apartment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "room"
                        });
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("int")
                        .HasColumnName("advertisementId");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("data");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Address", b =>
                {
                    b.HasOne("AdvertisingService.BusinessLogic.Models.Advertisement", "Advertisement")
                        .WithOne("Address")
                        .HasForeignKey("AdvertisingService.BusinessLogic.Models.Address", "AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Address_Advertisement");

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Advertisement", b =>
                {
                    b.HasOne("AdvertisingService.BusinessLogic.Models.Category", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Advertisement_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Image", b =>
                {
                    b.HasOne("AdvertisingService.BusinessLogic.Models.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Image_Advertisement");

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Advertisement", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("AdvertisingService.BusinessLogic.Models.Category", b =>
                {
                    b.Navigation("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
